/*
 * SPDX-FileCopyrightText: 2026
 * SPDX-License-Identifier: Apache-2.0
 * GENERATED by scripts/sign_update.py --genkey -- DO NOT EDIT by hand.
 * Public key that verifies signed OTA images (docs/ota_signing.md).
 */
#pragma once

static const char THELINK_FIRMWARE_PUBKEY_PEM[] =
"-----BEGIN PUBLIC KEY-----\n"
"MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAENjguwrUWyR6fgbv+hcW1uKDiHQMU\n"
"9tm5/KGMfdskQmWtMAcg1ZVcfdLBk18eEVj3AxGpSW0/lCgpHUDsA8uzPg==\n"
"-----END PUBLIC KEY-----\n"
;
