#!/usr/bin/env python3
"""
MQTT broker settings for the TheLink firmware: the broker address and the
credentials sent to it.

The firmware reads these from the CONFIG_BROKER_URL, CONFIG_MQTT_USERNAME and
CONFIG_MQTT_PASSWORD Kconfig symbols. Rather than making everyone find those in
menuconfig, scripts/build.py asks for them here and stores them in a Kconfig
overlay file, sdkconfig.secrets, which it then appends to SDKCONFIG_DEFAULTS.
The overlay is regenerated on every build: it is the cache, so the values are
only typed once, and it is gitignored so they stay out of the repository.

One rule runs through all of it: an empty value means "not specified", and a
field that was not specified is not written to the overlay. That is what keeps
CONFIG_BROKER_URL owned by menuconfig - the build prompt can override it, but
never silently pins it.

Sources, in order of precedence:

    Broker URL   : THELINK_BROKER_URL, then the value already in use, then a
                   prompt pre-filled with the value already in use.
    Credentials  : THELINK_MQTT_USERNAME + THELINK_MQTT_PASSWORD, then the
                   cached sdkconfig.secrets, then a prompt.

The last resort is no values at all, plus a warning: the build proceeds, the
broker URL comes from menuconfig, and the firmware connects anonymously.

Whichever source is used, the values end up in build*/sdkconfig and
build*/config/sdkconfig.h (both gitignored) and in the firmware image. That is
unavoidable when they are build-time options: a broker password has to be known
to the device in order to authenticate with it. Treat the built binary as
sensitive.
"""

import getpass
import os
import re
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Gitignored Kconfig overlay, also handed to idf.py as part of SDKCONFIG_DEFAULTS.
SECRETS_FILE = os.path.join(ROOT, "sdkconfig.secrets")
SECRETS_BASENAME = os.path.basename(SECRETS_FILE)

ENV_BROKER_URL = "THELINK_BROKER_URL"
ENV_USERNAME = "THELINK_MQTT_USERNAME"
ENV_PASSWORD = "THELINK_MQTT_PASSWORD"

# Mirrors the CONFIG_BROKER_URL default in main/Kconfig.projbuild. Only used to
# show a starting point when no previous build is available to read a value from.
DEFAULT_BROKER_URL = "mqtt://broker.emqx.io"

# The schemes esp-mqtt understands, in the order they are shown to the user.
SCHEMES = ("mqtt", "mqtts", "ws", "wss")

# Kconfig symbol -> environment variable, for the prompts and the log.
BROKER_URL = "BROKER_URL"
MQTT_USERNAME = "MQTT_USERNAME"
MQTT_PASSWORD = "MQTT_PASSWORD"

_CONFIG_LINE = re.compile(r'^\s*CONFIG_(?P<key>[A-Z_0-9]+)\s*=\s*"(?P<value>.*)"\s*$')

_BANNER = "----------------------------------------------------------------------"

_FILE_HEADER = """\
# Local MQTT broker settings for the TheLink firmware.
#
# Generated by scripts/build.py - edit it by hand if you like, but the next build
# will rewrite it. Gitignored; do not commit. Re-run the build with --reprompt
# to change the settings from the command line.
#
# A field that is missing here is not set by this file: CONFIG_BROKER_URL and the
# credentials then come from menuconfig instead.
#
# The values are also embedded in build*/sdkconfig and in the firmware image,
# so treat the resulting binary as sensitive.
"""


def _unescape(value):
    return value.replace('\\"', '"').replace("\\\\", "\\")


def _escape(value):
    return value.replace("\\", "\\\\").replace('"', '\\"')


def load():
    """Return the settings cached in sdkconfig.secrets as a dict.

    Only the fields present in the file are returned. Values are unescaped, so
    the result is what the firmware will see. A missing file or unparsable
    content yields whatever could be read, so a hand-edited overlay never
    crashes the build.
    """
    settings = {}
    try:
        with open(SECRETS_FILE, "r") as f:
            for line in f:
                line = line.strip()
                if not line or line.startswith("#"):
                    continue
                match = _CONFIG_LINE.match(line)
                if match:
                    settings[match.group("key")] = _unescape(match.group("value"))
    except OSError:
        pass
    return settings


def read_broker_url(sdkconfig_path):
    """The broker URL a previous build used, read from its generated sdkconfig.

    Returns None when there is no readable sdkconfig, i.e. on a first build.
    This is only used to pre-fill the prompt and as a fallback, so menuconfig
    stays the source of truth for CONFIG_BROKER_URL.
    """
    if not sdkconfig_path:
        return None
    try:
        with open(sdkconfig_path, "r") as f:
            for line in f:
                match = _CONFIG_LINE.match(line.strip())
                if match and match.group("key") == BROKER_URL:
                    return _unescape(match.group("value"))
    except OSError:
        pass
    return None


def _check_printable(value, field):
    """Reject values that cannot be represented in a Kconfig string."""
    for ch in value:
        if ord(ch) < 32 or ord(ch) == 127:
            raise ValueError("%s cannot contain control characters" % field)
    return value


def _check_broker_url(url):
    """Reject URLs esp-mqtt cannot use, so typos surface now, not on the device.

    esp-mqtt only knows these four schemes (esp_mqtt_transport_t); anything
    else fails at connect time with "Not support this mqtt scheme".
    """
    _check_printable(url, "Broker URL")
    scheme, sep, host = url.partition("://")
    if not sep or not scheme or not host:
        raise ValueError('Broker URL needs a scheme and a host, e.g. "%s"'
                         % DEFAULT_BROKER_URL)
    if scheme.lower() not in SCHEMES:
        raise ValueError("unsupported scheme %r, use one of %s"
                         % (scheme, ", ".join(SCHEMES)))
    return url


def write(settings):
    """Write the given settings to the sdkconfig.secrets overlay.

    `settings` is a dict of Kconfig symbol name -> value; only the fields it
    holds are written. Raises ValueError if a value cannot be represented as a
    Kconfig string, or if a password is given without a username.
    """
    for key in (BROKER_URL, MQTT_USERNAME, MQTT_PASSWORD):
        if key in settings:
            _check_printable(settings[key], key)
    if BROKER_URL in settings:
        _check_broker_url(settings[BROKER_URL])
    if settings.get(MQTT_PASSWORD) and not settings.get(MQTT_USERNAME):
        raise ValueError("an MQTT password needs an MQTT username")

    lines = [_FILE_HEADER.rstrip("\n")]
    for key in (BROKER_URL, MQTT_USERNAME, MQTT_PASSWORD):
        if key in settings:
            lines.append('CONFIG_%s="%s"' % (key, _escape(settings[key])))
    lines.append("")

    with open(SECRETS_FILE, "w") as f:
        f.write("\n".join(lines))
    if os.name != "nt":
        os.chmod(SECRETS_FILE, 0o600)


def _persist(settings, url_source, creds_source):
    """Store the settings so the build can pick them up. Returns them, or None."""
    try:
        write(settings)
    except (ValueError, OSError) as e:
        print("error: could not write %s: %s" % (SECRETS_BASENAME, e))
        print("       those settings will not reach the firmware.")
        return None
    if BROKER_URL in settings:
        print("  broker url      : %s (%s)" % (settings[BROKER_URL], url_source))
    if settings.get(MQTT_USERNAME):
        print("  mqtt username   : %s (%s)"
              % (settings[MQTT_USERNAME], creds_source))
    print("  saved to        : %s" % SECRETS_BASENAME)
    return settings


def _prompt(broker_url):
    """Ask for the broker URL, then the credentials.

    Returns a dict of the settings the user supplied, which is empty when they
    skipped. Each field left empty is simply left out, so the corresponding
    menuconfig option keeps applying. A rejected broker URL does not abort the
    prompt: it is dropped and the credential questions are still asked.
    """
    print("")
    print("MQTT broker settings")
    print("  Compiled into the firmware. Press Enter to leave a setting to")
    print("  menuconfig, or leave the username empty to build anonymously.")
    if broker_url:
        print("  Broker URL currently in use: %s" % broker_url)

    url = None
    try:
        url = input("Broker URL [%s]: " % (broker_url or DEFAULT_BROKER_URL)).strip()
    except (EOFError, KeyboardInterrupt):
        print("")
        return {}
    if url:
        try:
            _check_broker_url(url)
        except ValueError as e:
            print("error: %s - leaving the broker URL to menuconfig." % e)
            url = None

    try:
        username = input("MQTT username: ").strip()
    except (EOFError, KeyboardInterrupt):
        print("")
        return {BROKER_URL: url} if url else {}
    if not username:
        return {BROKER_URL: url} if url else {}

    try:
        password = getpass.getpass("MQTT password: ")
        if password and getpass.getpass("Confirm password: ") != password:
            print("Passwords did not match.")
            return {BROKER_URL: url} if url else {}
    except (EOFError, KeyboardInterrupt):
        print("")
        return {BROKER_URL: url} if url else {}
    except Exception as e:                      # no controlling terminal
        print("error: cannot read a password without a terminal (%s)." % e)
        print("       Set %s and %s instead, or rerun from a terminal."
              % (ENV_USERNAME, ENV_PASSWORD))
        return {BROKER_URL: url} if url else {}
    return {BROKER_URL: url, MQTT_USERNAME: username, MQTT_PASSWORD: password}


def warn_missing():
    """Explain the consequences of building without broker credentials."""
    print("")
    print(_BANNER)
    print("WARNING: no MQTT credentials - the firmware will connect anonymously")
    print(_BANNER)
    print("  A broker that requires authentication will refuse the connection.")
    print("  To fix this, run the build again from an interactive terminal and")
    print("  answer the prompt, or set these environment variables:")
    print("      %s=...  %s=...  %s=..."
          % (ENV_BROKER_URL, ENV_USERNAME, ENV_PASSWORD))
    print("  The prompt is skipped entirely when --no-prompt is given.")
    print("")


def resolve(sdkconfig_path=None, allow_prompt=True, force_prompt=False):
    """Work out the broker settings for this build and stage them.

    Returns a dict of the settings to apply, or None when the build should rely
    on menuconfig alone. The caller must only add SECRETS_BASENAME to
    SDKCONFIG_DEFAULTS when a dict comes back, so that a deliberate skip is not
    silently overridden by whatever the overlay file still holds.

    Note that the broker URL that a previous build used is only ever used to
    pre-fill the prompt. It is never written to the overlay, so menuconfig keeps
    ownership of CONFIG_BROKER_URL.
    """
    in_use = read_broker_url(sdkconfig_path)
    cached = {} if force_prompt else load()

    broker_url = None
    url_source = None
    creds_source = None

    if not force_prompt:
        env_url = os.environ.get(ENV_BROKER_URL)
        if env_url is not None:
            try:
                _check_broker_url(env_url)
                broker_url = env_url
                url_source = ENV_BROKER_URL
            except ValueError as e:
                print("error: %s: %s" % (ENV_BROKER_URL, e))
        if broker_url is None:
            broker_url = cached.get(BROKER_URL)
            if broker_url:
                url_source = SECRETS_BASENAME

    creds = None
    if not force_prompt:
        env_user = os.environ.get(ENV_USERNAME)
        env_pass = os.environ.get(ENV_PASSWORD)
        if env_user is not None and env_pass is not None:
            if env_user:
                creds = {MQTT_USERNAME: env_user, MQTT_PASSWORD: env_pass}
                creds_source = ENV_USERNAME
            else:
                print("%s is set but empty: no credentials." % ENV_USERNAME)
        elif env_user is None and env_pass is None and cached.get(MQTT_USERNAME):
            creds = {MQTT_USERNAME: cached[MQTT_USERNAME],
                     MQTT_PASSWORD: cached.get(MQTT_PASSWORD, "")}
            creds_source = SECRETS_BASENAME

    if creds is None:
        if not allow_prompt:
            print("No credentials resolved and --no-prompt was given.")
        elif not sys.stdin.isatty():
            print("stdin is not a terminal, so the MQTT broker prompt is skipped.")
            print("Set %s / %s / %s to build without typing them."
                  % (ENV_BROKER_URL, ENV_USERNAME, ENV_PASSWORD))
        else:
            answer = _prompt(broker_url or in_use or DEFAULT_BROKER_URL)
            if answer.get(BROKER_URL):
                broker_url = answer[BROKER_URL]
                url_source = "the prompt"
            if answer.get(MQTT_USERNAME):
                creds = {MQTT_USERNAME: answer[MQTT_USERNAME],
                         MQTT_PASSWORD: answer.get(MQTT_PASSWORD, "")}
                creds_source = "the prompt"

    settings = {}
    if broker_url:
        settings[BROKER_URL] = broker_url
    if creds:
        settings.update(creds)
    if not settings:
        # load() rather than `cached`, which force_prompt deliberately empties.
        if force_prompt and load():
            print("The settings in %s will NOT be used for this build."
                  % SECRETS_BASENAME)
        else:
            warn_missing()
        return None
    return _persist(settings, url_source, creds_source)
