#!/usr/bin/env python3
"""
TheLink firmware signing tool (Tier A: hash-then-sign, ECDSA P-256).

Computes SHA-256(image) and signs only that digest. The signature is written
to "<image>.sig" as a DER/ASN.1 ECDSA signature. On the device,
main.cpp's verify_firmware_signature() hashes the image, then verifies the
signature against the public key embedded in main/firmware_pubkey.h.

The private key lives in keys/firmware_signing.pem and must NEVER be
committed (keys/ is in .gitignore). The embedded public key and the public
pem are (re)generated with:

    python3 scripts/sign_update.py --genkey

Then REBUILD the firmware so it embeds the new public key: a device only
accepts images signed by the key whose public half it was built with.

Examples:
    python3 scripts/sign_update.py update.bin
    python3 scripts/sign_update.py --key keys/prod_signing.pem update.bin
    python3 scripts/sign_update.py --genkey
    python3 scripts/verify_update.py update.bin
"""

import argparse
import hashlib
import os
import stat
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_PRIV = os.path.join(ROOT, "keys", "firmware_signing.pem")
DEFAULT_PUB = os.path.join(ROOT, "keys", "firmware_signing_pub.pem")
DEFAULT_EMBED = os.path.join(ROOT, "main", "firmware_pubkey.h")


def _crypto():
    from cryptography.hazmat.primitives.asymmetric import ec
    from cryptography.hazmat.primitives.asymmetric.utils import Prehashed
    from cryptography.hazmat.primitives import hashes, serialization
    return ec, Prehashed, hashes, serialization


def load_or_create_key(path):
    ec, _, _, serialization = _crypto()
    if os.path.exists(path):
        with open(path, "rb") as f:
            return serialization.load_pem_private_key(f.read(), password=None)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    key = ec.generate_private_key(ec.SECP256R1())
    with open(path, "wb") as f:
        f.write(key.private_bytes(
            serialization.Encoding.PEM,
            serialization.PrivateFormat.PKCS8,
            serialization.NoEncryption()))
    os.chmod(path, stat.S_IRUSR | stat.S_IWUSR)
    print("Generated new signing key: %s (private key - never commit it!)" % path)
    return key


def public_key_pem(key):
    _, _, _, serialization = _crypto()
    return key.public_key().public_bytes(
        serialization.Encoding.PEM,
        serialization.PublicFormat.SubjectPublicKeyInfo).decode("ascii")


def write_embedded_header(pem_text, header_path):
    lines = [ln for ln in pem_text.splitlines() if ln]
    body = "".join('"%s\\n"\n' % ln for ln in lines)
    content = (
        "/*\n"
        " * SPDX-FileCopyrightText: 2026\n"
        " * SPDX-License-Identifier: Apache-2.0\n"
        " * GENERATED by scripts/sign_update.py --genkey -- DO NOT EDIT by hand.\n"
        " * Public key that verifies signed OTA images (docs/ota_signing.md).\n"
        " */\n"
        "#pragma once\n"
        "\n"
        "static const char THELINK_FIRMWARE_PUBKEY_PEM[] =\n"
        + body +
        ";\n"
    )
    with open(header_path, "w") as f:
        f.write(content)
    print("Embedded public key written to: %s" % header_path)


def sign_image(key, image_path, sig_path):
    ec, Prehashed, hashes, _ = _crypto()
    try:
        with open(image_path, "rb") as f:
            data = f.read()
    except OSError as e:
        sys.exit("error: cannot read image: %s" % e)

    digest = hashlib.sha256(data).digest()  # hash-then-sign: only the digest
    signature = key.sign(digest, ec.ECDSA(Prehashed(hashes.SHA256())))

    with open(sig_path, "wb") as f:
        f.write(signature)

    print("Signed  : %s (%d bytes)" % (image_path, len(data)))
    print("SHA-256 : %s" % digest.hex())
    print("Wrote   : %s (DER ECDSA P-256, %d bytes)" % (sig_path, len(signature)))


def main():
    parser = argparse.ArgumentParser(
        description="Sign (or generate keys for) theLink OTA firmware images.")
    parser.add_argument("image", nargs="?", default=None,
                        help="Firmware binary to sign (e.g. build/...app.bin)")
    parser.add_argument("--key", default=None, help="Private key PEM path")
    parser.add_argument("--out", default=None,
                        help="Signature output path (default: <image>.sig)")
    parser.add_argument("--pub", default=DEFAULT_PUB,
                        help="Public key PEM path (default: %s)" % DEFAULT_PUB)
    parser.add_argument("--embed", default=DEFAULT_EMBED,
                        help="Embedded public-key header (default: %s)" % DEFAULT_EMBED)
    parser.add_argument("--genkey", action="store_true",
                        help="Generate the signing key, public pem and embedded header")
    args = parser.parse_args()

    priv = args.key or DEFAULT_PRIV
    key = load_or_create_key(priv)

    if args.genkey:
        pem = public_key_pem(key)
        os.makedirs(os.path.dirname(args.pub), exist_ok=True)
        with open(args.pub, "w") as f:
            f.write(pem + "\n")
        print("Public key written to: %s" % args.pub)
        write_embedded_header(pem, args.embed)
        if args.image is None:
            return

    if args.image is None:
        sys.exit("error: no image given (pass a firmware binary or use --genkey)")

    sig_path = args.out or (args.image + ".sig")
    sign_image(key, args.image, sig_path)


if __name__ == "__main__":
    main()